name: Build agent-widget

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: For act to work (local testing)
        if: ${{ github.event.act }}
        run: npm -g install yarn

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Build agent-widget
        working-directory: ./agent-widget
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn deploy
