name: Build agent-widget

on:
  workflow_dispatch:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: For act to work (local testing)
        if: ${{ github.event.act }}
        run: npm -g install yarn

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Build and deploy agent-widget
        working-directory: ./agent-widget
        run: |
          yarn install --frozen-lockfile
          yarn build
          yarn deploy
